
name: BlackDuck Scan

on:
  # Triggers the workflow on push request events but only for the master branch
  pull_request:
    branches: [ master ]
  #push:
  #  branches: [ master ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Step 1
        run: echo "github.event.number -> ${{ github.event.number }}"
      - name: Step 2
        run: echo "github.event.number -> $GITHUB_EVENT_NUMBER"
      - name: Step 21
        run: echo "github.action-> $GITHUB_REF"
      - name: Step 22
        run: echo "github.actor-> $GITHUB_BASE_REF"
      - name: Step 23
        run: echo "github.base_ref-> $GITHUB_HEAD_REF"  
