
name: BlackDuck Scan

on:
  # Triggers the workflow on push request events but only for the master branch
  pull_request:
    branches: [ master ]
  #push:
  #  branches: [ master ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Step 1
        run: echo "${{github.action}}"
      - name: Step 2
        run: echo "${{github.actor}}"
      - name: Step 3
        run: echo "${{github.base_ref}}"
      - name: Step 4
        run: echo "${{github.event}}"
      - name: Step 5
        run: echo "${{github.event_name}}"
      - name: Step 6
        run: echo "${{github.event_path}}"
      - name: Step 7
        run: echo "${{github.head_ref}}"
      - name: Step 8
        run: echo "${{github.job}}"
      - name: Step 9
        run: echo "${{github.ref}}"
      - name: Step 10
        run: echo "${{github.repository}}"
      - name: Step 11
        run: echo "${{github.repository_owner}}"
      - name: Step 12
        run: echo "${{github.run_id}}"
      - name: Step 13
        run: echo "${{github.run_number}}"
      - name: Step 14
        run: echo "${{github.sha}}"
      - name: Step 15
        run: echo "${{github.token}}"
      - name: Step 16
        run: echo "${{github.workflow}}"
      - name: Step 17
        run: echo "${{github.head_ref}}"
      - name: Step 18
        run: echo "${{github.workspace}}"
      - name: Step 19
        run: echo "${{job.container.id}}"
      - name: Step 20
        run: echo "${{job.container}}"
